### ISSUE TITLE
gross php

### ISSUE THREAD

**Issue by haylinmoore** [DatOneLefty/ATC#1]
^

**Comment by lholliger** [comment]
do you mean stop using php, my formatting is terrible, there are security issues (in the code, not php), or i randomly used " and '

**Comment by haylinmoore** [comment]
nodeJS pls ;P

**Comment by towerofnix** [comment]
..if you don't explain why, nobody's going to change..

saying "nodeJS pls ;P" is really just going to make it look like you don't *care* enough to explain why to use nodeJS, which leads to making nodeJS looking bad....
