### ISSUE TITLE
post.php is not in the repository

### ISSUE THREAD

**Issue by towerofnix** [DatOneLefty/ATC#2]
Either you forgot to commit it, you forgot to push the commit with it to GitHub, or you're deliberately leaving it out of this repository (in which case, I'm curious why).

**Comment by towerofnix** [comment]
Looks to be fixed by commit 1197b49011dbcec1f4516c06fe12e8f53b0d65cd.

**Comment by lholliger** [comment]
stuff is kinda hard right now for me, my laptop broke so im writing on my mac and using TeamViewer to upload the files to my server, and then i need to remember to commit on my server. but ill be getting my laptop fixed in the next few months sooo

**Comment by haylinmoore** [comment]
Is your server not full terminal?

**Comment by lholliger** [comment]
im using plain Ubuntu 16.04, i run multiple services from it and having multiple windows makes stuff easier (i also dont really know how to run all of these processes and be able to watch and reload them using just 1 terminal)

**Comment by haylinmoore** [comment]
"man screen" it's really really nice I use it for lots of things. Forever js is also pretty great
